In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np
from matplotlib import font_manager, rc
font_path = "c:\WINDOWS\Fonts\GULIM.TTC"
font = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font)
plt.rc('font', size=8) 

In [2]:
dataframe = pd.read_csv(r'C:\Users\hyssk\AICE_\open\train.csv')
dataframe.drop(columns='ID',inplace=True)
dataframe

대출금액        대출기간       근로기간    주택소유상태       연간소득  부채_대비_소득_비율  \
0      12480000   36 months    6 years      RENT   72000000        18.90   
1      14400000   60 months  10+ years  MORTGAGE  130800000        22.33   
2      12000000   36 months    5 years  MORTGAGE   96000000         8.60   
3      14400000   36 months    8 years  MORTGAGE  132000000        15.09   
4      18000000   60 months    Unknown      RENT   71736000        25.39   
...         ...         ...        ...       ...        ...          ...   
96289  14400000   36 months  10+ years  MORTGAGE  210000000         9.33   
96290  28800000   60 months  10+ years  MORTGAGE  132000000         5.16   
96291  14400000   36 months     1 year  MORTGAGE   84000000        11.24   
96292  15600000   36 months    5 years  MORTGAGE   66330000        17.30   
96293   8640000   36 months  10+ years      RENT   50400000        11.80   

       총계좌수   대출목적  최근_2년간_연체_횟수    총상환원금     총상환이자  총연체금액  연체계좌수 대출등급  
0        15  부채 통합             0        0       0.0    0.0    0.0    C  
1        21  주택 개선             0   373572  234060.0    0.0    0.0    B  
2        14  부채 통합             0   928644  151944.0    0.0    0.0    A  
3        15  부채 통합             0   325824  153108.0    0.0    0.0    C  
4        19  주요 구매             0   228540  148956.0    0.0    0.0    B  
...     ...    ...           ...      ...       ...    ...    ...  ...  
96289    33  신용 카드             0   974580  492168.0    0.0    0.0    C  
96290    25  주택 개선             0   583728  855084.0    0.0    0.0    E  
96291    22  신용 카드             0  1489128  241236.0    0.0    0.0    A  
96292    21  부채 통합             2  1378368  818076.0    0.0    0.0    D  
96293    14  신용 카드             0   596148  274956.0    0.0    0.0    C  

[96294 rows x 14 columns]

In [3]:
dataframe['근로기간']=dataframe['근로기간'].replace('1 years','1 year')
dataframe['근로기간']=dataframe['근로기간'].replace('3','3 years')
dataframe['근로기간']=dataframe['근로기간'].replace('<1 year','< 1 year')
dataframe['근로기간']=dataframe['근로기간'].replace('10+years','10+ years')
dataframe['근로기간'].value_counts()

근로기간
10+ years    32481
2 years       8450
< 1 year      8144
3 years       7670
1 year        6305
Unknown       5671
5 years       5665
4 years       5588
8 years       4888
6 years       3874
7 years       3814
9 years       3744
Name: count, dtype: int64

# 범주형 데이터 전처리하기 (Pandas.factorize())

In [4]:
categorical_columns = dataframe.select_dtypes('object').columns
categorical_columns # 범주형 칼럼명들의 리스트

Index(['대출기간', '근로기간', '주택소유상태', '대출목적', '대출등급'], dtype='object')

In [5]:
dataframe[['대출기간']] = pd.factorize(dataframe['대출기간'])[0].reshape(-1,1)
dataframe[['대출기간']]

대출기간
0         0
1         1
2         0
3         0
4         1
...     ...
96289     0
96290     1
96291     0
96292     0
96293     0

[96294 rows x 1 columns]

In [6]:
dataframe['대출목적'].value_counts()

대출목적
부채 통합     55150
신용 카드     24500
주택 개선      6160
기타         4725
주요 구매      1803
의료         1039
자동차         797
소규모 사업      787
이사          506
휴가          466
주택          301
재생 에너지       60
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dataframe['대출목적'] = le.fit_transform(dataframe['대출목적'])
dataframe[['대출목적']]


대출목적
0         1
1        10
2         1
3         1
4         8
...     ...
96289     3
96290    10
96291     3
96292     1
96293     3

[96294 rows x 1 columns]

In [8]:
dataframe

대출금액  대출기간       근로기간    주택소유상태       연간소득  부채_대비_소득_비율  총계좌수  \
0      12480000     0    6 years      RENT   72000000        18.90    15   
1      14400000     1  10+ years  MORTGAGE  130800000        22.33    21   
2      12000000     0    5 years  MORTGAGE   96000000         8.60    14   
3      14400000     0    8 years  MORTGAGE  132000000        15.09    15   
4      18000000     1    Unknown      RENT   71736000        25.39    19   
...         ...   ...        ...       ...        ...          ...   ...   
96289  14400000     0  10+ years  MORTGAGE  210000000         9.33    33   
96290  28800000     1  10+ years  MORTGAGE  132000000         5.16    25   
96291  14400000     0     1 year  MORTGAGE   84000000        11.24    22   
96292  15600000     0    5 years  MORTGAGE   66330000        17.30    21   
96293   8640000     0  10+ years      RENT   50400000        11.80    14   

       대출목적  최근_2년간_연체_횟수    총상환원금     총상환이자  총연체금액  연체계좌수 대출등급  
0         1             0        0       0.0    0.0    0.0    C  
1        10             0   373572  234060.0    0.0    0.0    B  
2         1             0   928644  151944.0    0.0    0.0    A  
3         1             0   325824  153108.0    0.0    0.0    C  
4         8             0   228540  148956.0    0.0    0.0    B  
...     ...           ...      ...       ...    ...    ...  ...  
96289     3             0   974580  492168.0    0.0    0.0    C  
96290    10             0   583728  855084.0    0.0    0.0    E  
96291     3             0  1489128  241236.0    0.0    0.0    A  
96292     1             2  1378368  818076.0    0.0    0.0    D  
96293     3             0   596148  274956.0    0.0    0.0    C  

[96294 rows x 14 columns]

In [9]:
dataframe['주택소유상태'].values

array(['RENT', 'MORTGAGE', 'MORTGAGE', ..., 'MORTGAGE', 'MORTGAGE',
       'RENT'], dtype=object)

In [10]:
from sklearn.preprocessing import OneHotEncoder

oh=OneHotEncoder()
encoder = oh.fit_transform(dataframe[['주택소유상태']]).toarray()
print(f'OneHotEncoder 이해하기:',type(oh.fit_transform(dataframe[['주택소유상태']])))
print(f'OneHotEncoder.fit_transform 자료 \n',oh.fit_transform(dataframe[['주택소유상태']]).toarray())
print(f'OneHotEncode된 칼럼명들 : {oh.get_feature_names_out()}')
print(f'OneHotEncode 하려고하는 칼럼의 수준: {oh.categories_}')
print(f'OneHotEncoder의 feature_names_in_(어떤 칼럼이 인코딩되기 위해 입력됐는가?): {oh.feature_names_in_}')

OneHotEncoder 이해하기: <class 'scipy.sparse._csr.csr_matrix'>
OneHotEncoder.fit_transform 자료 
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
OneHotEncode된 칼럼명들 : ['주택소유상태_ANY' '주택소유상태_MORTGAGE' '주택소유상태_OWN' '주택소유상태_RENT']
OneHotEncode 하려고하는 칼럼의 수준: [array(['ANY', 'MORTGAGE', 'OWN', 'RENT'], dtype=object)]
OneHotEncoder의 feature_names_in_(어떤 칼럼이 인코딩되기 위해 입력됐는가?): ['주택소유상태']


In [11]:
dataframe[['주택소유상태']]

주택소유상태
0          RENT
1      MORTGAGE
2      MORTGAGE
3      MORTGAGE
4          RENT
...         ...
96289  MORTGAGE
96290  MORTGAGE
96291  MORTGAGE
96292  MORTGAGE
96293      RENT

[96294 rows x 1 columns]

In [12]:
encoded_state=pd.DataFrame(encoder, columns=oh.get_feature_names_out())
dataframe = pd.concat([dataframe,encoded_state],axis=1)
dataframe.drop(columns='주택소유상태',inplace=True)
dataframe

대출금액  대출기간       근로기간       연간소득  부채_대비_소득_비율  총계좌수  대출목적  \
0      12480000     0    6 years   72000000        18.90    15     1   
1      14400000     1  10+ years  130800000        22.33    21    10   
2      12000000     0    5 years   96000000         8.60    14     1   
3      14400000     0    8 years  132000000        15.09    15     1   
4      18000000     1    Unknown   71736000        25.39    19     8   
...         ...   ...        ...        ...          ...   ...   ...   
96289  14400000     0  10+ years  210000000         9.33    33     3   
96290  28800000     1  10+ years  132000000         5.16    25    10   
96291  14400000     0     1 year   84000000        11.24    22     3   
96292  15600000     0    5 years   66330000        17.30    21     1   
96293   8640000     0  10+ years   50400000        11.80    14     3   

       최근_2년간_연체_횟수    총상환원금     총상환이자  총연체금액  연체계좌수 대출등급  주택소유상태_ANY  \
0                 0        0       0.0    0.0    0.0    C         0.0   
1                 0   373572  234060.0    0.0    0.0    B         0.0   
2                 0   928644  151944.0    0.0    0.0    A         0.0   
3                 0   325824  153108.0    0.0    0.0    C         0.0   
4                 0   228540  148956.0    0.0    0.0    B         0.0   
...             ...      ...       ...    ...    ...  ...         ...   
96289             0   974580  492168.0    0.0    0.0    C         0.0   
96290             0   583728  855084.0    0.0    0.0    E         0.0   
96291             0  1489128  241236.0    0.0    0.0    A         0.0   
96292             2  1378368  818076.0    0.0    0.0    D         0.0   
96293             0   596148  274956.0    0.0    0.0    C         0.0   

       주택소유상태_MORTGAGE  주택소유상태_OWN  주택소유상태_RENT  
0                  0.0         0.0          1.0  
1                  1.0         0.0          0.0  
2                  1.0         0.0          0.0  
3                  1.0         0.0          0.0  
4                  0.0         0.0          1.0  
...                ...         ...          ...  
96289              1.0         0.0          0.0  
96290              1.0         0.0          0.0  
96291              1.0         0.0          0.0  
96292              1.0         0.0          0.0  
96293              0.0         0.0          1.0  

[96294 rows x 17 columns]